stages:
  - check
  - tfplan
  - maven_test
  - npm_test
  - dotnet_build
  - deploy_artifacts

include:
  - local: 'ci/tasks/*.yaml'

check:
  stage: check
  script:
    - echo $CI_PIPELINE_SOURCE
    - echo $TERRAFORM_CHANGES
    - echo $BACKEND_JAVA_CHANGES
    - echo $FRONTEND_CHANGES
    - ls -al changes
  rules:
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline"'
      when: always
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: checkout

terraform:
  stage: tfplan
  extends: .terraform-plan
  image: hashicorp/terraform:1.3.0
  rules:
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline" && $TERRAFORM_CHANGES == "true"'
      when: always
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: checkout

backend_java:
  stage: maven_test
  extends: .maven
  image: maven:3.8.6-openjdk-11
  rules:
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline" && $BACKEND_JAVA_CHANGES == "true"'
      when: always
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: checkout

frontend:
  stage: npm_test
  extends: .npm
  image: node:21.1.0
  rules:
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline" && $FRONTEND_CHANGES == "true"'
      when: always
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: checkout

backend_dotnet:
  stage: dotnet_build
  extends: .dotnet
  image: mcr.microsoft.com/dotnet/sdk:6.0
  rules:
    - if: '$CI_PIPELINE_SOURCE == "parent_pipeline" && $BACKEND_DOTNET_CHANGES == "true"'
      when: always
  needs:
    - pipeline: $PARENT_PIPELINE_ID
      job: checkout
